pugx_multi_user:
  users:
    insalade:
        entity: 
          class: Insalade\UserBundle\Entity\Insalade
        registration:
          form: 
            type: Insalade\UserBundle\Form\Type\RegistrationInsaladeFormType
          template: InsaladeUserBundle:Registration:insalade.form.html.twig
    amicale:
        entity: 
          class: Insalade\UserBundle\Entity\Amicale
        registration:
          form: 
            type: Insalade\UserBundle\Form\Type\RegistrationAmicaleFormType
          template: InsaladeUserBundle:Registration:amicale.form.html.twig
    asso:
        entity: 
          class: Insalade\UserBundle\Entity\Asso
        registration:
          form: 
            type: Insalade\UserBundle\Form\Type\RegistrationAssoFormType
          template: InsaladeUserBundle:Registration:asso.form.html.twig