services:
    user.registration.listener:
        class: Insalade\UserBundle\Listener\RegistrationListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
        arguments: ["@service_container"]