insalade_communication:
    resource: "@InsaladeCommunicationBundle/Controller/"
    type:     annotation
    prefix:   /

insalade_user2:
    resource: "@InsaladeUserBundle/Controller/"
    type:     annotation
    prefix:   /

insalade_user:
    resource: "@InsaladeUserBundle/Resources/config/routing.yml"

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"