# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    my.listener:
        class: Insalade\CommunicationBundle\Listener\CommunicationListener
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }